In [1]:
import numpy as np

In [2]:
arr=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [4]:
row=np.array([[12,23,45]])
re=np.concatenate((arr,row),axis=0)

In [5]:
re

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [12, 23, 45]])

In [6]:
import pandas as pd

In [7]:
#2
se=pd.Series([1,1,1,2,2,2,2,3,3,3,4,4,5])
f={}
for i in se:
    if i in f:
        f[i]+=1
    else:
        f[i]=1
h=pd.Series(f)
h

1    3
2    4
3    3
4    2
5    1
dtype: int64

In [9]:
#3
ser=pd.Series(np.random.randint(1,10,35))
df=pd.DataFrame({"index":ser.index,"values":ser.values})
df

index  values
0       0       2
1       1       5
2       2       5
3       3       6
4       4       8
5       5       7
6       6       2
7       7       4
8       8       1
9       9       9
10     10       4
11     11       4
12     12       3
13     13       1
14     14       4
15     15       3
16     16       6
17     17       3
18     18       4
19     19       4
20     20       8
21     21       5
22     22       4
23     23       1
24     24       4
25     25       8
26     26       6
27     27       9
28     28       5
29     29       7
30     30       7
31     31       6
32     32       6
33     33       7
34     34       6

In [10]:
#4
ser=pd.Series(np.random.randint(1,10,10))
for i in ser:
    if i%3==0:
        print(np.where(ser==i))
ser        

(array([1, 5], dtype=int64),)
(array([1, 5], dtype=int64),)
(array([9], dtype=int64),)


0    2
1    3
2    8
3    8
4    7
5    3
6    1
7    4
8    4
9    9
dtype: int32

In [12]:
#5
ser1=pd.Series(range(5))
ser2=pd.Series(list("abcde"))
ser3=pd.concat(([ser1,ser2]),ignore_index=True)
ser3

0    0
1    1
2    2
3    3
4    4
5    a
6    b
7    c
8    d
9    e
dtype: object

In [16]:
#6
exam_data = {
 'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
selected_columns = df[['name', 'score']]
print(selected_columns)

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [ ]:
)