In [1]:
import numpy as np

In [2]:
ar=np.arange()

In [3]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
ar=np.array([1,2,3,4,5,6])
ar11=np.reshape(2,3)
ar

ValueError: cannot reshape array of size 1 into shape (3,)

In [17]:
#identity matrix can be created using 2 functions
#eye()--> used to define both user defined rows and columns
#indentity()--> used to define same number of rows and columns
#syntax-->np.identity(5)--> 5 is 5 rows and 5 columns
#syntax-->np.eye(3,4)--> 3 rows and 4 columns
ar=np.eye(3,7)
print(ar)
ar2=np.identity(2)
print(ar2)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]
[[1. 0.]
 [0. 1.]]


In [15]:
ar=np.array([1,2,3,4,5,6])
ar11=ar.reshape(2,3)
ar11

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
ar=np.array([1,2,3,4,5,6])
arr2=ar.reshape(2,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
ar=np.identity(5,dtype=complex)

In [19]:
ar

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [20]:
#1.how to craete range of element as array
#2.how to convert a 1d array to multidimensional array
#3.how to create array of identity matrix
#4.how to perform slicing in multidimensional array
#5.how to find mean,median,sum,variance,standard deviation of an array
ar=np.arange(1,37)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [21]:
#2.how to convert a 1d array to multidimensional array
ar=np.array([1,2,3,4,5,6])
arr2=ar.reshape(2,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
#3.how to create array of identity matrix
ar=np.identity(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#to perform slicing of mutidimensional array
ar=np.arange(25).reshape(5,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ar.shape

(5, 5)

In [28]:
#ar[rows:columns,step]
#ar[row_start:row_end,column_start:col_end,step]
ar[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [29]:
ar[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
ar[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [31]:
ar[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [32]:
#tasks
#to positive and negative
#1)to print 27,28,37,38-->2
#2)print 34,35,44,45
#3)print 18,19
#4)print 31,31,40,41
np.sum(ar,axis=0)

array([50, 55, 60, 65, 70])

In [33]:
np.sum(ar, axis = 0) #to add on based on column wise
np.sum(ar, axis=1)# to add based on row wise axis=1 
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
np.sum(ar)

300

In [ ]:
#mean-->avg
#median-->center value
#mode-->max num of repeated element
#variance-->med/total num of ele
#std-->square root of variance

In [35]:
# linspace()-->evenly only separated
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [36]:
# it is used to print evenly separated  pointed
# betw 2 range of values
np.linspace(1,10,5,dtype=int)#--> linspace(start,end,number of values to be displayed between the numbers given in the range)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

np.linspace(1,37,2)

In [39]:
np.linspace(2,37,retstep=True)

(array([ 2.        ,  2.71428571,  3.42857143,  4.14285714,  4.85714286,
         5.57142857,  6.28571429,  7.        ,  7.71428571,  8.42857143,
         9.14285714,  9.85714286, 10.57142857, 11.28571429, 12.        ,
        12.71428571, 13.42857143, 14.14285714, 14.85714286, 15.57142857,
        16.28571429, 17.        , 17.71428571, 18.42857143, 19.14285714,
        19.85714286, 20.57142857, 21.28571429, 22.        , 22.71428571,
        23.42857143, 24.14285714, 24.85714286, 25.57142857, 26.28571429,
        27.        , 27.71428571, 28.42857143, 29.14285714, 29.85714286,
        30.57142857, 31.28571429, 32.        , 32.71428571, 33.42857143,
        34.14285714, 34.85714286, 35.57142857, 36.28571429, 37.        ]),
 0.7142857142857143)

In [40]:
#random module
#np.random.randint(start,end)
#to generate random numbers between the range
# np.random.randint(start,end)
np.random.randint(37)

11

In [41]:
#random module
#np.random.randint(start,end)
#to generate random numbers between the range
# np.random.randint(start,end,num_of_values)
#np.random,randint(40)
#or
np.random.randint(20,30,3)

array([24, 27, 20])

In [42]:
# rand()-->
# to get the randomly generated values from 0 to 1,based on 
# uniform distribution

np.random.rand(4)


array([0.91056188, 0.31766738, 0.35422503, 0.20660243])

In [ ]:
# to find the probability of tyhe rectangle = p(x)*(b-a)
# 1= p(x)*(b-a)

# p(x)= 1/(b-a)

In [43]:



np.random.rand(3,4)

array([[0.81599828, 0.18926491, 0.36250566, 0.07515466],
       [0.00569908, 0.96545258, 0.00450194, 0.71501783],
       [0.83113456, 0.63241983, 0.72538854, 0.72229077]])

In [44]:
# rand()-->
# to get the randomly generated values from 0 to 1,based on 
# normalised distribution

np.random.rand(5)

array([0.5333036 , 0.68299585, 0.10723735, 0.81218392, 0.25948021])

In [45]:
ar=np.arange(50).reshape(5,10)

In [46]:
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [47]:
ar[-1]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
ar[-1]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
ar[3:5,0:2]

array([[30, 31],
       [40, 41]])

In [54]:
ar[2:4,-3:-1]

array([[27, 28],
       [37, 38]])

In [56]:
# rand()-->
# to get the randomly generated values from 0 to 1,based on 
# normalised distribution

np.random.rand(5,4)

array([[0.68129476, 0.68537984, 0.94526776, 0.07559493],
       [0.89776048, 0.17017949, 0.87960268, 0.4983524 ],
       [0.23266234, 0.44636624, 0.40609848, 0.04095424],
       [0.28225376, 0.92982321, 0.21970021, 0.22143589],
       [0.98423606, 0.5662137 , 0.7506311 , 0.38511086]])

In [57]:
# prints the minimum value in the array
ar.min()

0

In [58]:
# prints the maximum value of the array
ar.max()

49

In [60]:
# to find the index of min values
l1=[1,2,3,4.5]
print (l1.index(3))

2


In [61]:
#conversion to list
print(ar.tolist())

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [62]:
# to get the index of the min and max values of the array
print(ar.argmin())
print(ar.argmax())

0
49


In [63]:
#type of array 
type(ar)

numpy.ndarray

In [69]:
np.sin(ar)
np.cos(ar)
np.tan(ar)


array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01,  1.15782128e+00, -3.38051501e+00,
        -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
         4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
         3.00632242e-01,  3.49391565e+00, -1.13731371e+00,
         1.51589471e-01],
       [ 2.23716094e+00, -1.52749853e+00,  8.85165604e-03,
         1.58815308e+00, -2.13489670e+00, -1.33526407e-01,
         1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
         8.87142844e-01],
       [-6.40533120e+00, -4.41695568e-01,  6.61006041e-01,
        -7.53130148e+01, -6.23498963e-01,  4.73814720e-01,
         7.75047091e+00, -8.40771255e-01,  3.10309661e-01,
         3.61455441e+00],
       [-1.11721493e+00,  1.60656699e-01,  2.29138799e+00,
        -1.49838734e+00,  1.77046993e-02,  1.61977519e+00,
        -2.08661353e+00, -1.24527568e-01,  1.20012724e+00,
        -3.

In [70]:
np.cos(ar)/np.sin(ar)

C:\Users\HARISREE AKULA\AppData\Local\Temp\ipykernel_19356\1618496009.py:1: RuntimeWarning: divide by zero encountered in divide
  np.cos(ar)/np.sin(ar)


array([[            inf,  6.42092616e-01, -4.57657554e-01,
        -7.01525255e+00,  8.63691154e-01, -2.95812916e-01,
        -3.43635300e+00,  1.14751542e+00, -1.47065064e-01,
        -2.21084541e+00],
       [ 1.54235105e+00, -4.42574133e-03, -1.57267341e+00,
         2.15972864e+00,  1.38033720e-01, -1.16823331e+00,
         3.32632320e+00,  2.86211833e-01, -8.79264876e-01,
         6.59676425e+00],
       [ 4.46995109e-01, -6.54665115e-01,  1.12973210e+02,
         6.29662222e-01, -4.68406739e-01, -7.48915531e+00,
         8.48353752e-01, -3.05464410e-01, -3.55328645e+00,
         1.12721419e+00],
       [-1.56119952e-01, -2.26400279e+00,  1.51284548e+00,
        -1.32779175e-02, -1.60385191e+00,  2.11052962e+00,
         1.29024418e-01, -1.18938414e+00,  3.22258739e+00,
         2.76659275e-01],
       [-8.95082918e-01,  6.22445256e+00,  4.36416706e-01,
        -6.67384176e-01,  5.64821794e+01,  6.17369624e-01,
        -4.79245430e-01, -8.03035035e+00,  8.33244979e-01,
        -3.

In [72]:
ar=np.arange(9).reshape(3,3)

In [73]:
R

NameError: name 'R' is not defined

In [74]:
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
#task-1 -->wrireb python code for the below logic
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
#(1*4)+(2*5)+(3*6)=32
ar5=ar1*ar2
ar6=ar5.sum()
ar6

32

In [80]:
fname =np.array(["sid","fn1","fn2"])
lname =np.array(["T","ln1","ln2"])
fname.tostring()

C:\Users\HARISREE AKULA\AppData\Local\Temp\ipykernel_19356\338870883.py:3: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  fname.tostring()


b's\x00\x00\x00i\x00\x00\x00d\x00\x00\x00f\x00\x00\x00n\x00\x00\x001\x00\x00\x00f\x00\x00\x00n\x00\x00\x002\x00\x00\x00'

In [81]:
fname =np.array(["sid","fn1","fn2"],dtype=str)
lname =np.array(["T","ln1","ln2"],dtype=str)
fname

array(['sid', 'fn1', 'fn2'], dtype='<U3')

In [84]:
#task-1:write a python code to add below 2 arrays
ar1=np.array([1,2,3,8,3,5])
ar2=np.array([4,5,6])
len1=len(ar1)
len2=len(ar2)
diff=abs(len1-len2)
for val in range(diff):
    ar2=np.append(ar2,1)
np.sum(ar1*ar2)    


48

In [85]:
ar1=np.array([1,34,56,78,np.nan,np.nan])
ar1

array([ 1., 34., 56., 78., nan, nan])

In [86]:
np.isnan(ar1)

array([False, False, False, False,  True,  True])

In [87]:
ar1[np.isnan(ar1)]

array([nan, nan])

In [88]:
#to eliminate nan values
ar1[~np.isnan(ar1)]

array([ 1., 34., 56., 78.])

In [89]:
#to print nan values
ar1[np.isnan(ar1)]

array([nan, nan])

In [90]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
np.dot(ar1,ar2)

32

In [92]:
pip list panda

Package                       Version
----------------------------- ---------------
aiobotocore                   2.5.0
aiofiles                      22.1.0
aiohttp                       3.8.5
aioitertools                  0.7.1
aiosignal                     1.2.0
aiosqlite                     0.18.0
alabaster                     0.7.12
anaconda-anon-usage           0.4.2
anaconda-catalogs             0.2.0
anaconda-client               1.12.1
anaconda-cloud-auth           0.1.3
anaconda-navigator            2.5.2
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
async-timeout                 4.0.2
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8

In [93]:
import panda as pd

ModuleNotFoundError: No module named 'panda'

In [94]:
import pandas as pd

In [95]:
#pandas is defined as a open source file which provides high perormance data manipulation in python
#data analysis require a alot of procesing such as restructuring,cleaning,merging,manipulatingetc.. we prefer pandas to perform the above functionalities because it is fast,simple than other tools.
#pandas is built on numpy,so it requires numpy ,numpy is required for operating pandas


In [96]:
#Panda series
# panda series is data structure with one cimensional labelled array
#it is a primary building block of data frame,making its rows and columns

In [97]:
labels=['a','b','c']
my_data=[10,20,30]
ar=np.array(my_data)
d={'a':100,"b":200,"c":300}


In [98]:
#syntax-->panda.series(data=None,index=None,dtype=None,name=None,copy=True or False)
#eg:1

In [99]:
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [100]:
type(pd.Series(my_data))

pandas.core.series.Series

In [101]:
#series with labels
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [102]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [105]:
pd.Series(data=[print,len,sum])

0    <built-in function print>
1      <built-in function len>
2      <built-in function sum>
dtype: object

In [106]:
class profile:
    def display(self):
        print("My name is hari")
p=profile()
p.display()

My name is hari


In [116]:
#class profile:
 #  def display(self):
  #      print("My name is hari")
# p=profile()
# p.display

def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner
@decor
def greet():
    return "good morning"
print(greet())    

GOOD MORNING


In [121]:
ser1=pd.Series([1,2,3],["USA","India","Egypt"])
ser1

USA      1
India    2
Egypt    3
dtype: int64

In [122]:
ser1["USA"]

1

In [123]:
#accessing values using index
ser1[0]

1

In [124]:
ser2=pd.Series([5,6],["Qatar","canada"])

In [125]:
ser1=ser2

In [126]:
ser1

Qatar     5
canada    6
dtype: int64

In [131]:
ser2["canada"]="duplicate"

In [132]:
ser2

Qatar             5
canada    duplicate
dtype: object

In [133]:
ser2.drop("Qatar")

canada    duplicate
dtype: object

In [134]:
#DataFrame
#pd.DataFrame(datas,row_label,col_label)

In [141]:
df=pd.DataFrame(np.random.randn(5,4))

In [142]:
df

0         1         2         3
0 -0.706616  1.151292  0.136912 -0.476902
1  0.727368  0.985683 -0.795745  0.017697
2 -2.277531  0.976255  0.280310 -0.266099
3  0.515554  0.991220 -0.724134  0.665746
4  0.878313  1.451115  0.555750 -0.360847

In [139]:
df=pd.DataFrame(np.random.randn(5,4),["a","b","c","d","e"],["w","x","y","z"])

In [140]:
df

w         x         y         z
a  0.666821 -2.373338 -0.225365 -1.384262
b -0.981552  0.860017 -0.070786  0.296883
c -0.715427  1.199786 -0.427783  0.470657
d  0.120875  0.188401 -0.686944  1.254712
e  1.117924 -1.805816 -0.800856  0.838297

In [146]:
#to convert dictionary to DataFrame
d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}
d

{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

df=pd.DataFrame(data=d)

In [145]:
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [7]:
import pandas as pd
d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}
d
df=pd.DataFrame(d,["row1","row2"])

In [8]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [9]:
df.index

Index(['row1', 'row2'], dtype='object')

In [10]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [11]:
df.T

row1  row2
col1     1     2
col2     3     4
col3     5     6

In [12]:
#get all rows
df.index

Index(['row1', 'row2'], dtype='object')

In [13]:
#get all columns
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [15]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df.dtypes

col1    int64
col2    int64
col3    int64
dtype: object

In [19]:
#to gert information about the dataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      int64
 1   col2    2 non-null      int64
 2   col3    2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes


In [20]:
df.values

array([[1, 3, 5],
       [2, 4, 6]], dtype=int64)

In [21]:
df.axes

[Index(['row1', 'row2'], dtype='object'),
 Index(['col1', 'col2', 'col3'], dtype='object')]

In [22]:
df.info

<bound method DataFrame.info of       col1  col2  col3
row1     1     3     5
row2     2     4     6>

In [23]:
df.index

Index(['row1', 'row2'], dtype='object')

In [24]:
df.ndim

2

In [25]:
df.size

6

In [26]:
#to access specific column in data frame
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [27]:
df["col1"]

row1    1
row2    2
Name: col1, dtype: int64

In [30]:
type(df["col1"])

pandas.core.series.Series

In [32]:
# inorder to access multiple columns
df[["col1","col2"]]

col1  col2
row1     1     3
row2     2     4

#to create new column
df["new"]=df["col1"]+df["col2"]

In [33]:
#to create new column 
df["new"]=df["col1"]+df["col2"]

In [34]:
df

col1  col2  col3  new
row1     1     3     5    4
row2     2     4     6    6

In [37]:
df.drop("new",axis=1)

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [38]:
df

col1  col2  col3  new
row1     1     3     5    4
row2     2     4     6    6

In [39]:
df.drop("new",axis=1,inplace=True)

In [40]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [ ]:
#to access rows  